# Generated by Django 4.2 on 2023-04-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_birthdate_user_is_employee_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(
                error_messages={"username": ["username already taken."]},
                max_length=127,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"email": ["email already registered."]},
                max_length=50,
                unique=True,
            ),
        ),
    ]
