# Generated by Django 4.2 on 2023-04-14 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_alter_movie_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="added_by",
        ),
    ]
