# Generated by Django 4.2 on 2023-04-14 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_movie_added_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="added_by",
        ),
    ]
